In [6]:
import numpy as np
import pandas as pd

### Day 1

In [12]:
data = np.loadtxt('1.txt')
n = int(len(data))
idx = 0
for i in range(1, n):
    diff = data[i] - data[i-1]
    if diff > 0:
        idx = idx + 1
print( idx)

second = np.zeros(n-2)
for i in range(2, n):
    second[i-2] = np.sum(data[i-2:i+1])
n = int(len(second))
idx = 0
for i in range(1, n):
    diff = second[i] - second[i-1]
    if diff > 0:
        idx = idx + 1
print( idx )

1167
1130


### Day 2

In [17]:
data = pd.read_csv( '2.txt', header = None, sep = ' ')
data = data.to_numpy()
n = int(len(data[:,0]))
deep = 0
hor = 0
for i in range(n):
    if data[i,0] == 'forward':
        hor = hor +  data[i,1]  
    if data[i,0] == 'down':
        deep = deep +  data[i,1] 
    if data[i,0] == 'up':
        deep = deep -  data[i,1] 
print( hor, deep, hor*deep )

deep = 0
hor = 0
aim = 0
for i in range(n):
    if data[i,0] == 'forward':
        hor = hor +  data[i,1]  
        deep = deep + aim*data[i,1]
    if data[i,0] == 'down':
        aim = aim +  data[i,1] 
    if data[i,0] == 'up':
        aim = aim -  data[i,1] 
print( hor, deep, hor*deep )

2007 747 1499229
2007 668080 1340836560


In [26]:
np.loadtxt?

In [61]:
data = np.loadtxt('3.txt', dtype='str')
n = int(len(data[:]))
print( n)
N = 12
values = np.zeros(12)
print( values)
for k in range(N):
    for i in range(n):
        values[k] = values[k] + int(data[i][k])
    if values[k] /n > 0.5:
        values[k] = 1
    else:
        values[k] = 0
print( values)

1000
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0.]


In [49]:
print( int('011111101100', base = 2) *int('100000010011', base = 2) )

4191876


In [140]:
data = np.loadtxt('3.txt', dtype='str')
n = int(len(data[:]))
print( n)
N = 12
values = np.zeros(12)
print( values)
for k in range(N):
    for i in range(n):
        values[k] = values[k] + int(data[i][k])
    if values[k] /n > 0.5:
        values[k] = 1
    else:
        values[k] = 0
print( values )

""" creo maschera per tenere i valori """
mask = np.ones(n)
m = n
for k in range(N):
    #print( k )
    for i in range(n):
        if mask[i] == 1:
            if int(data[i][k]) == values[k]:
                #print( 'qui')
                mask[i] = 1
            else:
                mask[i] = 0
    # Aggiorno array piu probabile
    values = np.zeros(12)
    for j in range(N):
        m = np.sum(mask) 
        # I have to divide for the effective length
        for t in range(n):
            if mask[t] == 1:
                values[j] = values[j] + int(data[t][j])
        # For oxygen, if equally common, I keep 1
        if values[j] /m >= 0.5:
            values[j] = 1
        else:
            values[j] = 0
    print( k, np.sum(mask))

for i in range(n):
    if mask[i] == 1:
        print( i, 'oxygen',  data[i] )

1000
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0.]
0 513.0
1 257.0
2 132.0
3 69.0
4 44.0
5 22.0
6 11.0
7 6.0
8 3.0
9 2.0
10 2.0
11 1.0
940 oxygen 010101101111


In [139]:
data = np.loadtxt('3.txt', dtype='str')
n = int(len(data[:]))
print( n)
N = 12
values = np.zeros(12)
print( values)
for k in range(N):
    for i in range(n):
        values[k] = values[k] + int(data[i][k])
    if values[k] /n > 0.5:
        values[k] = 1
    else:
        values[k] = 0
print( values )

""" creo maschera per tenere i valori """
mask = np.ones(n)
m = n
for k in range(N):
    for i in range(n):
        if mask[i] == 1:
            # i want to keep the less common
            if int(data[i][k]) == values[k]:
                #print( 'qui')
                mask[i] = 0
            else:
                mask[i] = 1
    # Values is always the array of the most probable value
    values = np.zeros(12)
    for j in range(N):
        m = np.sum( mask )
        # I want to divide for the effective length
        for t in range(n):
            if mask[t] == 1:
                values[j] = values[j] + int(data[t][j])
                
        if values[j] /m >= 0.5:
            values[j] = 1
        else:
            values[j] = 0

    m = np.sum(mask)
    print( k, m)
    if m == 1:
        for i in range(n):
            if mask[i] == 1:
                print( i, 'c02',  data[i] )                  

1000
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0.]
0 487.0
1 225.0
2 112.0
3 54.0
4 23.0
5 11.0
6 5.0
7 2.0
8 1.0
147 c02 100110010111
9 0.0
10 0.0
11 0.0


/home/gianmarco/.local/lib/python3.7/site-packages/ipykernel_launcher.py:37: RuntimeWarning: invalid value encountered in double_scalars


In [141]:
print( int('010101101111', base = 2) ) 
print( int('100110010111', base = 2) )

1391
2455


3414905


In [19]:
chain = np.loadtxt('6.txt', delimiter = ',')
days = 256
for i in range(days):
    n = int(len(chain))
    for j in range(n):
        if chain[j] == 0:
            chain[j] = 6
            chain = np.append(chain, 8)
        else:
            chain[j] = chain[j] - 1
    print( i , n)
print( int(len(chain)))

0 300
1 300
2 399
3 456
4 499
5 547
6 600
7 600
8 600
9 699
10 756
11 898
12 1003
13 1099
14 1147
15 1200
16 1299
17 1356
18 1597
19 1759
20 1997
21 2150
22 2299
23 2446
24 2556
25 2896
26 3115
27 3594
28 3909
29 4296
30 4596
31 4855
32 5342
33 5671
34 6490
35 7024
36 7890
37 8505
38 9151
39 9938
40 10526
41 11832
42 12695
43 14380
44 15529
45 17041
46 18443
47 19677
48 21770
49 23221
50 26212
51 28224
52 31421
53 33972
54 36718
55 40213
56 42898
57 47982
58 51445
59 57633
60 62196
61 68139
62 74185
63 79616
64 88195
65 94343
66 105615
67 113641
68 125772
69 136381
70 147755
71 162380
72 173959
73 193810
74 207984
75 231387
76 250022
77 273527
78 298761
79 321714
80 356190
81 381943


KeyboardInterrupt: 

In [150]:
from functools import lru_cache
#@lru_cache(maxsize = 128, typed = True)

def birth( fish, days, n):
    
    while n < days:
        fish[n] = fish[n] + 1
        #fish[n+8] = fish[n+8] + 1
        fish = birth( fish, days, n + 9)
        #n = days
        n = n + 7        
    return fish 
        
chain = np.loadtxt('test.txt', delimiter = ',')
days = 256
c = int(len(chain))
fish = np.zeros(  days + 9)
for i in range(int(len(chain))):
    n = int(chain[i] )
    #print( n)
    fish = birth( fish, days, n)

print( np.sum(fish[:days]) + c )


KeyboardInterrupt: 

In [169]:
from functools import lru_cache
@lru_cache(maxsize = 128, typed = True)
def birth(i, days):

    idx = 0
    while i < days:
        idx = idx + 1
        idx = idx + birth(i+9, days)
        i = i + 7
    return idx       
chain = np.loadtxt('test.txt', delimiter = ',')
days = 256


c = int(len(chain))
fish = 0
for i in range(int(len(chain))):
    n = int(chain[i] )
    #print( n)
    fish = fish + birth(n, days)
print( fish + c  )

1617359101538


In [15]:
days = 
fish = np.zeros(  days + 8)
fish = birth( fish, days, 1)
print( fish)

[0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1.]


### Day 7

In [64]:
chain = np.loadtxt('7.txt', delimiter = ',', dtype = 'int')
s = np.max( chain)
n = int(len(chain))
print( n, s)
cost = np.zeros(s-1)
t = np.arange( 1, s, 1)
p = np.zeros(s)
#print( t )
for i in range( 1, s ): 
    l = 0
    for j in range(n):
        idx = np.abs(chain[j] - i )
        # I can define an array that at each index has the 
        #sum up to that index
        l = l + np.sum(t[:idx])
    cost[i-1] = l 
    #cost[i-1] = np.sum( np.abs(chain - i))
print( np.min(cost) )

1000 1952
[   1    2    3 ... 1949 1950 1951]
91257582.0


### Day 8


In [38]:
#I put my reference values
uno = sum( [ord(char) for char in 'dgebacf'])
print( uno )
due = sum( [ord(char) for char in 'gcbe'])
print( due )
tre = sum( [ord(char) for char in 'cgb'])
print( tre )
quattro = sum( [ord(char) for char in 'gc'])
print( quattro ) 
cinque = sum( [ord(char) for char in 'ca'])
print( cinque ) 

700
401
300
202
196


In [43]:
data = pd.read_csv('8.txt', sep =' ', header = None)
data = data.to_numpy()
n = int(len(data[:,0]))
m = int(len(data[0,:]))
change = 11
count = 0
for i in range(n):
    for k in range(change, m):
        l = [ ord(char) for char in data[i,k]]
        l = len(l)
        if l == 2:
            count = count +1 
        if l == 3:
            count = count +1 
        if l == 4:
            count = count +1 
        if l == 7:
            count = count +1 
print( count )

288


In [31]:
def create_numbers( l ):
    numbers = np.zeros(10)
    #Find 1
    for k in l:
        if len(k) == 2:
            c = [k]
            l.remove(k)
            numbers[1] = sum([ord(s) for s in k ])
    #find 7 
    for k in l:
        if len(k) == 3:
            c.append(k)
            l.remove(k)
            numbers[7] = sum([ord(s) for s in k ])
    #find 4
    for k in l:
        if len(k) == 4:
            c.append(k)
            l.remove(k)
            numbers[4] = sum([ord(s) for s in k ])
    #find 3 it has all the strings of the seven 
    for k in l:
        if(len(k)) == 5:
            b = 0
            for char in k:
                if char in c[1]:
                    b = b +1
            if b == 3:
                c.append(k)
                l.remove(k)
                numbers[3] = sum([ord(s) for s in k ])
    # find 8
    for k in l:
        if len(k) == 7:
            c.append(k)
            l.remove(k)
            numbers[8] = sum([ord(s) for s in k ])
    #find 6 
    for k in l:
        if len(k) == 6:
            b = 0 
            for char in c[0]:
                if char in k:
                    b = b +1
            if b == 1:
                c.append(k)
                l.remove(k)
                numbers[6] = sum([ord(s) for s in k ])
    #find 9 
    for k in l:
        if len(k) == 6:
            b = 0 
            for char in c[2]:
                if char in k:
                    b = b +1
            if b == 4:
                c.append(k)
                l.remove(k)
                numbers[9] = sum([ord(s) for s in k ])
    #find 0
    for k in l:
        if len(k) == 6:
            c.append(k)
            l.remove(k)
            numbers[0] = sum([ord(s) for s in k ])
    #find 5
    for k in l:
        if len(k) == 5:
            b = 0 
            for char in c[5]:
                if char in k:
                    b = b +1
            if b == 5:
                c.append(k)
                l.remove(k)
                numbers[5] = sum([ord(s) for s in k ])
    #find2 
    for k in l:
        c.append(k)
        numbers[2] = sum([ord(s) for s in k ])
    myorder = [7, 0, 9, 3, 2, 8, 5, 1, 4, 6 ]
    mylist = [c[i] for i in myorder]
    return( mylist )

data = pd.read_csv('8.txt', sep =' ', header = None)
data = data.to_numpy()
n = int(len(data[:,0]))
#print( n )
count = 0
for i in range(n):
    
    l = [ s for s in data[i,:10]]
    numbers = create_numbers(l)
    l = [s for s in data[i,11:]]
    num = []
    for k in range(4):
        
        s = l[k]
        for j in range(10):
            if ''.join(sorted(numbers[j])) == ''.join(sorted(s)):
                num.append(str(j) )
                
    #print( int(''.join(num)) )
    count = count + int(''.join(num) )

print( count  )

940724


In [25]:
a = 'abs'
b = 'bsc'
print( ''.join(sorted(a)) )
print( ''.join(sorted(b)) )
if ''.join(sorted(a)) == ''.join(sorted(b)):
    print( 'qui')

abs
bcs


In [ ]:
    l = [ s for s in data[i,:10]]
    numbers = create_numbers(l)
    l = [s for s in data[i,11:]]
    num = []
    print( l )
    for k in range(4):
        
        s = sum([ord(c) for c in l[k] ] )
        for j in range(10):
            if s == numbers[j]:
                #print( s )
                num.append(str(j) )
                
    print( int(''.join(num)) )
    count = count + int(''.join(num) )

print( count  )

### Day 9

In [5]:
data  = np.loadtxt('test.txt', dtype = 'str')
n = int(len( data[:]))
print( n)
t = [ int(char) for char in data[0]]
l = int(len(t))
mask = np.zeros((n,l))
count = 0
# Add an higher value at the boundary to avoid boundary problems
# It is smarter than check the last line
# modfiyt it before going next
for i in range(1, n-1):
    t = [ int(char) for char in data[i-1]]
    m = [ int(char) for char in data[i]]
    b = [ int(char) for char in data[i+1]]
    l = int(len(m))
    for j in range(l):
        if j == 0:
            if m[j] < m[j+1] and m[j] < t[j] and m[j] < b[j]:
                count = count + 1 +m[j]
                mask[i,j] = 1
        elif j == l-1 :
            if m[j] < m[j-1] and m[j] < t[j] and m[j] < b[j]:
                count = count + 1  +m[j]
                mask[i,j] = 1
        else:
            if m[j] < m[j-1] and m[j] < m[j+1] and m[j] < t[j] and m[j] < b[j]:
                mask[i,j] = 1
                count = count + 1 + m[j]  

#i = 1
i = 0
m = [ int(char) for char in data[i]]
b = [ int(char) for char in data[i+1]]
for j in range(l):
    if j == 0:
        if m[j] < m[j+1]  and m[j] < b[j]:
            mask[i,j] = 1
            count = count + 1+m[j]
    elif j == l-1 :
        if m[j] < m[j-1] and m[j] < b[j]:
            count = count + 1  +m[j]
            mask[i,j] = 1
    else:
        if m[j] < m[j-1] and m[j] < m[j+1]  and m[j] < b[j]:
            mask[i,j] = 1
            count = count + 1 + m[j]     

i = n-1
m = [ int(char) for char in data[i]]
t = [ int(char) for char in data[i-1]]
for j in range(l):
    if j == 0:
        if m[j] < m[j+1]  and m[j] < t[j]:
            count = count + 1+m[j]
            mask[i,j] = 1
    elif j == l-1 :
        if m[j] < m[j-1] and m[j] < t[j]:
            count = count + 1  +m[j]
            mask[i,j] = 1
    else:
        if m[j] < m[j-1] and m[j] < m[j+1]  and m[j] < t[j]:
            mask[i,j] = 1
            count = count + 1 + m[j]   

print( mask )


NameError: name 'np' is not defined

[10  1  2  3]
