In [2]:
import numpy as np
import pandas as pd

In [85]:
f = open("day9.txt", "r")
Lines = f.read().splitlines()
nrow = len(Lines)
ncol = len(Lines[0])
numbers = np.zeros( ( nrow, ncol), dtype = int )

for i in range(nrow):
    line = Lines[i]
    j = 0;
    for s in line:
        numbers[i,j] = int(s)
        j = j+1
data = np.ones((nrow+2, ncol+2))*10
data[1:nrow+1,1:ncol+1] = numbers
data = data
print( data )
count = 0
size = []
for i in range(1,nrow+1):
    for j in range(1,ncol+1):
        if data[i,j] < data[i+1,j] and data[i,j] < data[i-1,j] and  data[i,j] < data[i,j-1] and  data[i,j] < data[i,j+1]:
            count = count + data[i,j] +1 
            mask =  np.zeros((nrow+2, ncol+2))
            mask[i,j] = 1
            find_basin(data, i, j)
            size.append(mask.sum() )

print( count )
size = np.flip(np.sort(size) )
print( size )
print( size[0]*size[1]*size[2] )

[[10. 10. 10. ... 10. 10. 10.]
 [10.  3.  5. ...  6.  7. 10.]
 [10.  2.  6. ...  5.  6. 10.]
 ...
 [10.  9.  8. ...  3.  4. 10.]
 [10.  8.  7. ...  4.  5. 10.]
 [10. 10. 10. ... 10. 10. 10.]]
566.0
[102.  94.  93.  87.  83.  83.  82.  81.  80.  79.  79.  78.  78.  78.
  75.  74.  74.  71.  70.  70.  70.  69.  69.  68.  67.  67.  66.  66.
  64.  63.  63.  61.  61.  60.  59.  58.  57.  56.  56.  56.  55.  54.
  54.  54.  53.  53.  53.  52.  52.  51.  51.  50.  50.  49.  48.  48.
  48.  48.  47.  47.  47.  45.  45.  44.  43.  42.  42.  42.  42.  41.
  41.  41.  40.  40.  40.  39.  39.  38.  37.  37.  37.  36.  36.  35.
  35.  35.  35.  35.  35.  33.  33.  32.  32.  32.  32.  31.  30.  30.
  29.  29.  28.  28.  28.  27.  27.  27.  27.  27.  27.  26.  26.  26.
  26.  26.  26.  26.  25.  25.  25.  25.  24.  24.  24.  22.  22.  22.
  21.  21.  20.  20.  20.  20.  20.  20.  20.  19.  19.  19.  19.  18.
  18.  18.  18.  18.  17.  17.  16.  16.  16.  15.  15.  15.  15.  15.
  15.  15.  14.  14. 

In [83]:
def find_basin(array, l, m):
    global mask
    a = [-1, 0, 0, 1]
    b = [0, 1, -1, 0]
    
    for i in range(4):
        x = a[i]
        y = b[i]
        
        #if array[l+x, m+y] == array[l,m] +1 and array[l+x,m+y] < 9:# and mask[l+x, m+y] == 0:
        if array[l+x,m+y] < 9 and mask[l+x,m+y] == 0:#
            mask[l+x, m+y] = 1 
            find_basin(array, l+x, m+y)
        
