In [1]:
import numpy as np
import pandas as pd

In [66]:
f = open("test.txt", "r")
Lines = f.read().splitlines()
nrow = len(Lines)
ncol = len(Lines[0])
numbers = np.zeros( ( nrow, ncol), dtype = int )

for i in range(nrow):
    line = Lines[i]
    j = 0;
    for s in line:
        numbers[i,j] = int(s)
        j = j+1
data = np.ones((nrow+2, ncol+2))*10
data[1:nrow+1,1:ncol+1] = numbers
data = data + 1
print( data )
count = 0
for i in range(1,nrow+1):
    for j in range(1,ncol+1):
        if data[i,j] < data[i+1,j] and data[i,j] < data[i-1,j] and  data[i,j] < data[i,j-1] and  data[i,j] < data[i,j+1]:
            count = count + data[i,j]
print( count )

[[11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [11.  3.  2. 10. 10. 10.  5.  4.  3.  2.  1. 11.]
 [11.  4. 10.  9.  8.  9. 10.  5. 10.  3.  2. 11.]
 [11. 10.  9.  6.  7.  8.  9. 10.  9. 10.  3. 11.]
 [11.  9.  8.  7.  8.  9. 10.  7.  8.  9. 10. 11.]
 [11. 10.  9. 10. 10. 10.  7.  6.  7.  8.  9. 11.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]]
15.0


In [34]:
#define recursive function to find basin 