In [2]:
import numpy as np
import pandas as pd

In [58]:
def create_map(array):
    
    nrow = int(len(array[0,:]))
    ncol = int(len(array[:,0]))
    
    mappa = np.zeros((5*nrow, 5*ncol))
    for i in range(5):
        for j in range(5):
            mappa[i*nrow:(i+1)*nrow,j*ncol:(j+1)*ncol ] = array + i + j
            # Posso farlo alla fine
            mappa[mappa > 9 ] = ( mappa[mappa > 9 ]%10 )+ 1
    return mappa 

In [59]:
f = open("day15.txt", "r")
Lines = f.read().splitlines()
nrow = len(Lines)
ncol = len(Lines[0])
numbers = np.zeros( ( nrow, ncol), dtype = int )

for i in range(nrow):
    line = Lines[i]
    j = 0;
    for s in line:
        numbers[i,j] = int(s)
        j = j+1
data = np.zeros((nrow+2,ncol+2))
check = np.zeros((nrow+2,ncol+2))
data[1:nrow+1,1:ncol+1] = numbers
print( numbers )
numbers = create_map(numbers)
print( numbers )
print( int(len(numbers[0,:])), int(len(numbers[:,0])))
#Faccio solo destra e sinistra? 
#provo così va

[[6 8 9 ... 4 7 4]
 [5 3 7 ... 2 9 8]
 [8 7 9 ... 8 5 1]
 ...
 [9 1 2 ... 8 5 6]
 [3 7 9 ... 5 8 4]
 [9 9 8 ... 8 9 2]]
[[6. 8. 9. ... 8. 2. 8.]
 [5. 3. 7. ... 6. 4. 3.]
 [8. 7. 9. ... 3. 9. 5.]
 ...
 [4. 5. 6. ... 7. 4. 5.]
 [7. 2. 4. ... 4. 7. 3.]
 [4. 4. 3. ... 7. 8. 1.]]
500 500


In [60]:
#I want to create all the paths and then value the price of each path
# I have to do 10 step down and then step right
nrow = 5*nrow
ncol = 5*ncol
costi = np.zeros((nrow, ncol))
costi[nrow-1, ncol-1] = numbers[nrow-1, ncol-1]
print( costi )
def cost(posx, posy, array):
    global costi
    global nrow
    global ncol
    costo_giu = 1000000
    costo_destra = 100000
    if posy + 1 < nrow:
        costo_giu = costi[posx][posy+1] if costi[posx][posy+1] != 0 else cost(posx, posy+1, array )
    
    if posx +1 < ncol:
        costo_destra = costi[posx+1][posy] if costi[posx+1][posy] != 0 else cost(posx+1, posy, array )     
    
    c = min( costo_destra, costo_giu)
    costi[posx][posy] = array[posx][posy] + c
    
    return costi[posx][posy]

cost( 0, 0, numbers) - numbers[0,0]

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


3068.0

In [32]:
nrow = 5*nrow
ncol = 5*ncol
costi = np.zeros((nrow,ncol))
cost(0,0, mappa) - mappa[0,0]

100181.0

In [4]:
a = 3
b = 5
min(3, 5)

3